sudo: required
services:
  - docker

before_install:
  - docker build -t joisandresky/eatbana-api .

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "eatbana-2"
  env: "Eatbana2-env"
  bucket_name: "elasticbeanstalk-us-east-2-505365354191"
  bucket_path: "eatbana-2"
  on:
    branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key:
      secure: "$AWS_SECRET_KEY"